import re

import streamlit as st
import pandas as pd
import altair as alt
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Table,
    TableStyle,
    Image,
    PageBreak,
    Spacer,
    KeepTogether
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER

from ratios import (
    current_ratio,
    quick_ratio,
    cash_ratio,
    working_capital,
    gross_profit_margin,
    operating_profit_margin,
    net_profit_margin,
    debtor_turnover,
    debtor_days,
    inventory_turnover,
    inventory_days,
    creditor_turnover,
    creditor_days,
    asset_turnover,
    debt_to_equity,
    debt_ratio,
    equity_ratio,
    interest_coverage_ratio,
    return_on_equity,
    return_on_assets,
    return_on_capital_employed,
    format_ratio
)
from analysis import (
    liquidity_analysis,
    profitability_analysis,
    debt_analysis,
    gross_margin_analysis,
    roe_analysis,
    efficiency_analysis
)


def add_page_number(canvas, doc):
    page_num = canvas.getPageNumber()
    canvas.setFont("Helvetica", 9)
    canvas.drawRightString(
        550,
        20,
        f"Page {page_num}"
    )
    # Branding footer on every page, not just the cover — so a report
    # that's been forwarded or printed on its own still identifies where
    # it came from.
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#6E6759"))
    canvas.drawString(
        40,
        20,
        "Generated by the Financial Ratio Analysis Tool"
    )


st.set_page_config(
    page_title="Financial Ratio Analysis Tool",
    page_icon="📊",
    layout="wide"
)

# ---------------- Brand / Theme ----------------
# A warm, "old-ledger" navy-and-brass palette instead of a cool grey/white
# one — ivory backgrounds and a deepened navy read closer to a bound
# accounting ledger or a private bank's stationery than a generic SaaS
# dashboard. GOLD is tuned to an actual brass hue (warmer, more orange)
# rather than the previous olive-gold, while keeping the exact same
# accessibility bar: #9B6526 carries 4.9:1 contrast against white and
# 4.62:1 against the new ivory background in both directions (as
# text-on-background and as white-on-fill), clearing the 4.5:1 the W3C
# requires for normal text either way.

# Dark/light mode toggle — a plain session_state flag (not Streamlit's own
# theme system, which is fixed at server start via config.toml and can't be
# swapped per-visitor at runtime). Everything below reads this flag and
# picks one of two palettes; both are pre-verified for WCAG contrast.
if "dark_mode" not in st.session_state:
    st.session_state["dark_mode"] = False
DARK_MODE = st.session_state["dark_mode"]

# Always these exact colours, regardless of mode — used only for surfaces
# that stay fixed either way: the monogram mark (always a dark square with
# this exact brass letter — it's a logo, not themed UI, so it shouldn't
# shift shade when the rest of the app switches to dark mode) and
# insight-card text (the cards themselves stay white/light in both modes,
# so their text must stay dark to remain readable on them).
BRAND_NAVY = "#0A1930"
BRAND_GOLD = "#9B6526"

if DARK_MODE:
    NAVY = "#F0E9DB"
    NAVY_LIGHT = "#5885C2"
    GOLD = "#C9873F"
    GOLD_HOVER = "#E0A05C"
    MUTED = "#B8AC8E"
    BORDER = "#2C4160"
    IVORY = "#0A1930"
    PANEL = "#13233D"
    CATEGORY_COLORS = {
        "Liquidity": "#4A88C7",
        "Profitability": "#329462",
        "Efficiency": "#BF6F4B",
        "Leverage": "#B26AAC",
        "Returns": "#2A9188",
    }
    TONE_COLORS = {
        "good": "#329462",
        "medium": "#AB7B44",
        "bad": "#C96565",
        "unavailable": "#8A8272",
        "info": "#5885C2",
        "warning": "#A67C49",
    }
else:
    NAVY = "#0A1930"
    NAVY_LIGHT = "#1E3A5F"
    GOLD = "#9B6526"
    GOLD_HOVER = "#7C501E"
    MUTED = "#6E6759"
    BORDER = "#E4DAC8"
    IVORY = "#FAF8F4"
    PANEL = "#F0E9DB"
    # One accent colour per ratio category — used only for small tags/
    # labels, never as a big colour block, so the app stays "classic"
    # rather than turning into a rainbow. Deepened to richer jewel tones
    # to sit well against the warmer ivory background; each still carries
    # 6:1+ contrast against both white and ivory.
    CATEGORY_COLORS = {
        "Liquidity": "#1B4C7E",
        "Profitability": "#1C6B43",
        "Efficiency": "#A34E27",
        "Leverage": "#6B3566",
        "Returns": "#0C6860",
    }
    # Custom callout tones — deliberately not Streamlit's default
    # st.success/st.info/st.warning/st.error, whose stock green/blue/
    # orange/red fill colours clash with a navy-and-brass palette and read
    # as generic "Bootstrap alert" rather than part of a designed report.
    TONE_COLORS = {
        "good": "#1C6B43",
        "medium": GOLD,
        "bad": "#7A2E2E",
        "unavailable": MUTED,
        "info": NAVY_LIGHT,
        "warning": "#9C6B2F",
    }


def styled_note(text, tone):
    color = TONE_COLORS.get(tone, MUTED)
    st.markdown(
        f"""
        <div style="border-left:4px solid {color}; background:#FFFFFF;
                    padding:0.85rem 1.15rem; border-radius:4px; margin-bottom:0.65rem;
                    box-shadow:0 1px 3px rgba(10,25,48,0.06);">
          <div style="color:{BRAND_NAVY}; font-size:0.95rem; line-height:1.55;">{text}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_insight(result):
    """result is a (message, severity) tuple from analysis.py. The card's
    accent colour always matches what the message says — a ratio that
    couldn't be calculated is a neutral note, not a green success card,
    and a genuinely weak ratio is a deep-red flag, not a cheerful one."""
    text, severity = result
    styled_note(text, severity)


def money_fmt(x):
    """Format a currency amount, correctly handling negative values.
    A naive f-string (f"£{x:,.0f}") renders a loss or negative working
    capital as the malformed "£-12,000"; this puts the minus sign before
    the currency symbol instead ("-£12,000"), which is how real accounts
    are actually written."""
    sign = "-" if x < 0 else ""
    return f"{sign}£{abs(x):,.0f}"


def inject_custom_css():
    st.markdown(
        f"""
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Source+Serif+4:wght@600;700&display=swap');

        html, body, [class*="css"] {{
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
        }}

        h1, h2, h3 {{
            font-family: 'Source Serif 4', Georgia, serif !important;
            color: {NAVY} !important;
            font-weight: 700 !important;
        }}

        [data-testid="stAppViewContainer"] {{
            background-color: {IVORY};
        }}

        /* ---- Streamlit's own native header/toolbar strip (the bar that
           holds the "⋮" menu) — this sits outside the app's own container
           and stays the fixed light theme colour unless overridden here,
           which is what left a stray pale bar across the top in dark mode. ---- */
        [data-testid="stHeader"] {{
            background-color: {IVORY} !important;
        }}
        [data-testid="stMainMenuButton"],
        [data-testid="stMainMenuButton"] svg {{
            color: {NAVY} !important;
            fill: {NAVY} !important;
        }}

        /* ---- Streamlit Community Cloud's own Share/Star/Fork/GitHub
           toolbar buttons — injected into this same header when the app is
           actually deployed (they don't render locally, which is why this
           was missed the first time round). The "Share" text label is
           real text and takes a plain colour override like everything
           else. The Star/Edit/GitHub icons, though, are each baked as a
           fixed-colour SVG background-image (colour hardcoded into the
           image bytes at render time, not a live element) — `color` and
           `fill` genuinely cannot repaint those, confirmed by inspecting
           the actual data URI. A CSS filter is the only way to recolour a
           background-image: invert(1) flips that hardcoded dark navy into
           a light, legible tone (and happens to land close to this app's
           own warm palette) — applied only in dark mode, since inverting
           them in light mode would make them invisible instead. ---- */
        [data-testid="stToolbarActionButton"],
        [data-testid="stToolbarActionButton"] button,
        [data-testid="stToolbarActionButtonLabel"] {{
            color: {NAVY} !important;
            fill: {NAVY} !important;
        }}
        [data-testid="stToolbarActionButtonIcon"] {{
            {"filter: invert(1);" if DARK_MODE else "filter: none;"}
        }}

        /* ---- st.caption() text — Streamlit renders these at a fixed
           navy-at-60%-opacity derived from config.toml's static theme, so
           in dark mode the text colour is nearly the same as the dark
           background behind it and effectively disappears. Overriding with
           the dynamic muted tone keeps captions legible in both modes. ---- */
        [data-testid="stCaptionContainer"] {{
            opacity: 1 !important;
        }}
        [data-testid="stCaptionContainer"] p,
        [data-testid="stCaptionContainer"] span,
        [data-testid="stCaptionContainer"] small {{
            color: {MUTED} !important;
        }}

        /* ---- Sidebar: light and quiet, used only for data upload ---- */
        [data-testid="stSidebar"] {{
            background-color: {PANEL};
            border-right: 1px solid {BORDER};
        }}
        [data-testid="stSidebar"] h1,
        [data-testid="stSidebar"] h2,
        [data-testid="stSidebar"] h3 {{
            color: {NAVY} !important;
            font-size: 1.05rem !important;
        }}

        /* ---- Top navigation bar ----
           Stays on a single line always — never wraps to a second row,
           per explicit request. If the window gets too narrow to fit
           every tab, the row scrolls horizontally within itself instead
           of breaking onto a new line or overlapping other content. The
           logo/wordmark column still grows to fill the leftover space
           (as it did originally), which is what keeps the same open gap
           before the nav tabs rather than crowding them right up against
           the wordmark. */
        .st-key-topnav {{
            border-bottom: 1px solid {BORDER};
            padding-bottom: 0.6rem;
            margin-bottom: 1.8rem;
        }}
        .st-key-topnav [data-testid="stHorizontalBlock"] {{
            flex-wrap: nowrap !important;
            align-items: center !important;
            overflow-x: auto !important;
            overflow-y: visible !important;
            padding-bottom: 4px !important;
            scrollbar-width: thin;
        }}
        .st-key-topnav [data-testid="stHorizontalBlock"] > div[data-testid="stColumn"] {{
            width: auto !important;
            min-width: 0 !important;
            flex: 0 0 auto !important;
        }}
        .st-key-topnav [data-testid="stHorizontalBlock"] > div[data-testid="stColumn"]:first-child {{
            flex: 1 1 auto !important;
            min-width: 180px !important;
        }}
        .st-key-topnav button {{
            white-space: nowrap;
        }}
        .st-key-topnav button p {{
            white-space: nowrap;
            font-size: 0.92rem !important;
            letter-spacing: 0.02em;
        }}
        /* Below ~950px even the tightened nav can't fit five tabs plus the
           wordmark on one line without scrolling — shrink the wordmark
           text itself first so more of the actual nav stays in view
           before anyone has to scroll sideways to reach "About". */
        @media (max-width: 950px) {{
            .st-key-topnav .topnav-wordmark {{
                font-size: 0.95rem !important;
            }}
        }}
        /* Underline-tab nav rather than filled pill buttons — reads as an
           editorial/financial masthead rather than a row of app buttons. */
        .st-key-topnav button[kind="secondary"],
        .st-key-topnav [data-testid="stBaseButton-secondary"] {{
            background-color: transparent !important;
            color: {MUTED} !important;
            border: none !important;
            border-bottom: 2px solid transparent !important;
            border-radius: 0 !important;
            box-shadow: none !important;
            font-weight: 500 !important;
            padding: 0.5rem 0.15rem 0.45rem 0.15rem !important;
        }}
        .st-key-topnav button[kind="secondary"]:hover,
        .st-key-topnav [data-testid="stBaseButton-secondary"]:hover {{
            background-color: transparent !important;
            color: {NAVY} !important;
            border-bottom: 2px solid {BORDER} !important;
        }}
        .st-key-topnav button[kind="primary"],
        .st-key-topnav [data-testid="stBaseButton-primary"] {{
            background-color: transparent !important;
            color: {NAVY} !important;
            border: none !important;
            border-bottom: 2px solid {GOLD} !important;
            border-radius: 0 !important;
            font-weight: 700 !important;
            padding: 0.5rem 0.15rem 0.45rem 0.15rem !important;
            box-shadow: none !important;
        }}

        /* ---- Buttons (elsewhere in the app) ---- */
        .stButton > button, .stDownloadButton > button {{
            background-color: {GOLD};
            color: #FFFFFF;
            border: none;
            border-radius: 8px;
            font-weight: 600;
            padding: 0.55rem 1.4rem;
            transition: background-color 0.15s ease;
        }}
        .stButton > button:hover, .stDownloadButton > button:hover {{
            background-color: {GOLD_HOVER};
            color: #FFFFFF;
        }}

        /* ---- About page — contact links styled as plain outlined pills,
           matching the tag chips used elsewhere, rather than filled brass
           buttons (this is informational, not a call to action). ---- */
        .about-contact-link {{
            display: inline-flex;
            align-items: center;
            gap: 0.5rem;
            background: {PANEL};
            border: 1px solid {BORDER};
            color: {NAVY} !important;
            font-size: 0.9rem;
            font-weight: 600;
            padding: 0.55rem 1.1rem;
            border-radius: 20px;
            text-decoration: none !important;
            transition: border-color 0.15s ease, color 0.15s ease;
        }}
        .about-contact-link:hover {{
            border-color: {GOLD};
            color: {GOLD} !important;
        }}

        /* ---- Light/dark toggle — a small, quiet icon button, deliberately
           not styled like the brass call-to-action buttons above, so it
           reads as a utility control rather than competing for attention.
           Lives as the last item in the nav row itself (see render_topbar)
           — the row is locked to a single line at every width, so this
           never gets orphaned onto its own line the way it used to. ---- */
        .st-key-theme_toggle button {{
            background-color: transparent !important;
            border: 1px solid {BORDER} !important;
            border-radius: 50% !important;
            color: {NAVY} !important;
            width: 2.4rem !important;
            padding: 0.3rem !important;
        }}
        .st-key-theme_toggle button:hover {{
            border-color: {GOLD} !important;
            background-color: transparent !important;
        }}

        /* ---- Native input widgets. Streamlit's own theme (config.toml's
           secondaryBackgroundColor) tints every input box with the panel
           colour by default — in light mode that reads as an unwanted tan
           highlight sitting behind Revenue, Cost of Sales, and every other
           field, which isn't the plain look the app is meant to have.
           Forced to plain white in light mode; kept as the dark panel
           colour in dark mode, where it's needed for contrast against the
           dark page. ---- */
        [data-testid="stNumberInput"] input,
        [data-testid="stTextInput"] input,
        [data-testid="stNumberInput"] div,
        [data-testid="stSelectbox"] div[data-baseweb="select"] > div {{
            background-color: {PANEL if DARK_MODE else "#FFFFFF"} !important;
            color: {NAVY} !important;
            border-color: {BORDER} !important;
        }}
        [data-testid="stFileUploaderDropzone"] {{
            background-color: {PANEL} !important;
            border-color: {BORDER} !important;
        }}
        [data-testid="stFileUploaderDropzoneInstructions"] span,
        [data-testid="stFileUploaderDropzoneInstructions"] small {{
            color: {MUTED} !important;
        }}
        [data-testid="stWidgetLabel"] p {{
            color: {NAVY} !important;
        }}
        [data-testid="stRadioOption"] [data-testid="stMarkdownContainer"] p {{
            color: {NAVY} !important;
        }}

        /* ---- Metrics ---- */
        [data-testid="stMetricValue"] {{
            color: {NAVY};
            font-weight: 700;
        }}
        [data-testid="stMetricLabel"] {{
            color: {MUTED};
            text-transform: uppercase;
            letter-spacing: 0.06em;
            font-size: 0.78rem;
            font-weight: 600;
        }}

        /* ---- Bordered containers used as flat cards ---- */
        div[data-testid="stVerticalBlockBorderWrapper"] {{
            border-radius: 6px !important;
            border-color: {BORDER} !important;
            background-color: {PANEL} !important;
            box-shadow: 0 1px 3px rgba(10,25,48,0.07) !important;
        }}

        /* One colour-coded accent stripe per ratio category, on the
           Ratio Analysis dashboard tiles — a common "premium dashboard
           card" cue rather than a flat, undifferentiated grid. */
        .st-key-tile_liquidity div[data-testid="stVerticalBlockBorderWrapper"] {{ border-top: 3px solid {CATEGORY_COLORS['Liquidity']} !important; }}
        .st-key-tile_profitability div[data-testid="stVerticalBlockBorderWrapper"] {{ border-top: 3px solid {CATEGORY_COLORS['Profitability']} !important; }}
        .st-key-tile_efficiency div[data-testid="stVerticalBlockBorderWrapper"] {{ border-top: 3px solid {CATEGORY_COLORS['Efficiency']} !important; }}
        .st-key-tile_leverage div[data-testid="stVerticalBlockBorderWrapper"] {{ border-top: 3px solid {CATEGORY_COLORS['Leverage']} !important; }}
        .st-key-tile_returns div[data-testid="stVerticalBlockBorderWrapper"] {{ border-top: 3px solid {CATEGORY_COLORS['Returns']} !important; }}


        /* ---- Dataframes ---- */
        [data-testid="stDataFrame"] {{
            border-radius: 8px;
            overflow: hidden;
            border: 1px solid {BORDER};
        }}

        /* ---- Tabs (Company A / Company B on the Home page) ---- */
        .stTabs [data-baseweb="tab-list"] {{
            gap: 1.5rem;
        }}
        .stTabs [aria-selected="true"] {{
            color: {NAVY} !important;
            font-weight: 700 !important;
        }}

        hr {{
            border-color: {BORDER};
        }}
        </style>
        """,
        unsafe_allow_html=True,
    )


NAV_PAGES = ["Home", "Ratio Analysis", "Company Comparison", "Financial Report", "About"]


def render_topbar():
    """A flat, underline-tab top navigation bar: a small monogram mark and
    serif wordmark on the left, plain text tabs and the theme toggle on the
    right, all on one line — the row no longer wraps at any width (see the
    CSS above), so the toggle can live right in the nav flow instead of
    needing to be pinned separately."""
    with st.container(key="topnav"):
        cols = st.columns([2.2, 1, 1, 1, 1, 1, 0.45])
        with cols[0]:
            st.markdown(
                f"""
                <div style="display:flex; align-items:center; gap:0.65rem;
                            padding-top:0.35rem; white-space:nowrap;">
                  <div style="width:1.9rem; height:1.9rem; border-radius:5px;
                              background:{BRAND_NAVY}; display:flex; align-items:center;
                              justify-content:center; flex-shrink:0;">
                    <span style="font-family:'Source Serif 4', Georgia, serif;
                                 font-weight:700; font-size:1.05rem; color:{BRAND_GOLD};">F</span>
                  </div>
                  <span class="topnav-wordmark" style="font-family:'Source Serif 4', Georgia, serif;
                               font-weight:700; font-size:1.12rem; color:{NAVY}; white-space:nowrap;">
                    Financial Ratio Analysis Tool
                  </span>
                </div>
                """,
                unsafe_allow_html=True,
            )
        for col, name in zip(cols[1:6], NAV_PAGES):
            with col:
                is_active = st.session_state.get("active_page", "Home") == name
                if st.button(
                    name,
                    key=f"nav_{name}",
                    type="primary" if is_active else "secondary",
                ):
                    st.session_state["active_page"] = name
                    st.rerun()
        with cols[6]:
            # A small, self-built light/dark toggle — Streamlit's own theme
            # switcher is unavailable whenever a custom [theme] is set in
            # config.toml, so this reads and flips its own session_state
            # flag instead and swaps the whole palette computed above. Sits
            # right in the nav row, last item, on the same single line as
            # everything else (the row no longer wraps at any width).
            icon = "☀️" if DARK_MODE else "\U0001f319"
            if st.button(icon, key="theme_toggle", help="Switch between light and dark mode"):
                st.session_state["dark_mode"] = not DARK_MODE
                st.rerun()


def render_page_header(title, subtitle):
    """A flat, document-style page header — a short brass accent bar and
    the serif title, no decorative icon, plus a muted one-line description."""
    st.markdown(
        f"""
        <div style="margin-bottom:1.6rem;">
          <div style="display:flex; align-items:center; gap:0.75rem;">
            <div style="width:5px; height:1.6rem; background:{GOLD}; border-radius:2px; flex-shrink:0;"></div>
            <div style="font-family:'Source Serif 4', Georgia, serif; font-weight:700;
                        font-size:1.85rem; color:{NAVY}; line-height:1.2;">
              {title}
            </div>
          </div>
          <div style="color:{MUTED}; font-size:0.98rem; margin-top:0.45rem; margin-left:1.4rem;">
            {subtitle}
          </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_bar_chart(data, color=GOLD, height=320):
    """Render a styled Altair bar chart from a single-column DataFrame
    whose index holds the category names (matches the shape previously
    passed to st.bar_chart throughout this app)."""
    df = data.reset_index()
    df.columns = ["Category", "Amount"]
    chart = (
        alt.Chart(df)
        .mark_bar(cornerRadiusTopLeft=4, cornerRadiusTopRight=4, size=54)
        .encode(
            x=alt.X("Category:N", sort=None, title=None, axis=alt.Axis(labelAngle=0)),
            y=alt.Y("Amount:Q", title="Amount (£)", axis=alt.Axis(format=",.0f")),
            color=alt.value(color),
            tooltip=[
                alt.Tooltip("Category:N", title="Item"),
                alt.Tooltip("Amount:Q", title="Amount", format=",.0f"),
            ],
        )
        .properties(height=height)
        .configure_axis(gridColor="#EDE6D8", domainColor=BORDER, tickColor=BORDER)
        .configure_view(strokeWidth=0)
    )
    st.altair_chart(chart, width="stretch")


def render_chart_or_table(data, color=GOLD, height=320, key=None):
    """Render a bar chart with an explicit, always-visible Chart/Table
    toggle above it, rather than relying on the chart's own hover toolbar.

    Altair/Vega charts in Streamlit already have a built-in "Show data"
    icon that swaps the chart for a plain table — but that toolbar only
    appears on mouse hover, and once you're looking at the table there's
    nothing on screen to show a "Show chart" option exists until you hover
    over the table again. That's easy to miss, which is exactly what made
    it look like there was no way back. This gives the same choice through
    a plain, permanently visible control instead."""
    view = st.radio(
        "View as",
        ["Chart", "Table"],
        horizontal=True,
        key=f"view_toggle_{key}" if key else None,
        label_visibility="collapsed",
    )
    if view == "Table":
        table_df = data.reset_index()
        table_df.columns = ["Category", "Amount"]
        st.dataframe(table_df, hide_index=True, width="stretch")
    else:
        render_bar_chart(data, color=color, height=height)


inject_custom_css()

# ---------------- Read Financial Data (flexible upload) ----------------

from data_extraction import extract_financial_data, METRIC_LABELS, OPTIONAL_METRICS

METRICS = list(METRIC_LABELS.keys())

# The 15 fields grouped the way an accountant would read a set of
# statements — income statement first, then the balance sheet split into
# current items and everything else — rather than one flat, unlabeled
# grid of 15 number inputs.
FIELD_GROUPS = [
    ("Income Statement", [
        "revenue", "cost_of_sales", "gross_profit",
        "operating_profit", "net_profit", "interest_expense",
    ]),
    ("Current Assets & Liabilities", [
        "current_assets", "inventory", "accounts_receivable",
        "cash", "current_liabilities", "accounts_payable",
    ]),
    ("Other Balance Sheet", [
        "total_assets", "total_debt", "equity",
    ]),
]


def _prettify_filename(filename):
    """Turn 'Acme_Financials_2024.xlsx' into 'Acme Financials 2024' for use
    as a default company name. Short all-caps tokens (e.g. 'PLC') are left
    as-is rather than title-cased."""
    base = re.sub(r"\.[^.]+$", "", str(filename))
    base = re.sub(r"[_\-]+", " ", base).strip()
    base = re.sub(r"\s+", " ", base)
    words = []
    for w in base.split(" "):
        if w.isupper() and 1 < len(w) <= 5:
            words.append(w)
        else:
            words.append(w.capitalize())
    return " ".join(words)


def sync_company_data(prefix, uploaded_file, default_path, label):
    """
    Runs auto-detection only when the uploaded file actually changes (not
    on every rerun), and seeds st.session_state[f"{prefix}_values"] — a
    plain dict, not a widget-bound key — with the detected values. The
    same pattern is used for the company name: a plain session_state
    string, refreshed only when the file changes, and otherwise editable
    without being clobbered.

    Using a plain dict/string (rather than reading widget keys directly)
    matters because Streamlit clears a widget's session_state entry
    whenever that widget isn't rendered in a given script run (e.g. after
    navigating away from the Home page). Storing values outside any
    widget keeps them available on every page regardless of which
    widgets are currently visible.
    """
    if uploaded_file is not None:
        file_key = f"{uploaded_file.name}:{uploaded_file.size}"
        source, filename = uploaded_file, uploaded_file.name
        guessed_name = _prettify_filename(uploaded_file.name)
    else:
        file_key = "__default__"
        source, filename = default_path, default_path
        guessed_name = label

    state_key = f"{prefix}_file_key"
    if st.session_state.get(state_key) != file_key:
        values, meta = extract_financial_data(source, filename)
        st.session_state[state_key] = file_key
        st.session_state[f"{prefix}_meta"] = meta or {}
        st.session_state[f"{prefix}_extract_error"] = (meta or {}).get("error") or (meta or {}).get("warning")
        st.session_state[f"{prefix}_values"] = {
            metric: float((values or {}).get(metric, 0.0)) for metric in METRICS
        }
        st.session_state[f"{prefix}_default_company_name"] = guessed_name
        st.session_state[f"{prefix}_company_name"] = guessed_name

    if f"{prefix}_values" not in st.session_state:
        st.session_state[f"{prefix}_values"] = {metric: 0.0 for metric in METRICS}
    if f"{prefix}_company_name" not in st.session_state:
        st.session_state[f"{prefix}_company_name"] = label


def company_values(prefix):
    return dict(st.session_state[f"{prefix}_values"])


RATIO_CATEGORIES = ["Liquidity", "Profitability", "Efficiency", "Leverage", "Returns"]


def compute_ratio_set(v):
    """The full "professional scale" ratio set, computed and formatted in
    one place so the Ratio Analysis breakdown, Company Comparison table,
    and PDF report all show exactly the same numbers rather than three
    separate re-implementations drifting apart. v is a dict shaped like
    company_values(prefix) — one of the 15 raw line items per key.
    Returns a list of (category, label, formatted_value) tuples."""
    money = money_fmt
    return [
        ("Liquidity", "Current Ratio",
         format_ratio(current_ratio(v["current_assets"], v["current_liabilities"]))),
        ("Liquidity", "Quick Ratio (Acid-Test)",
         format_ratio(quick_ratio(v["current_assets"], v["inventory"], v["current_liabilities"]))),
        ("Liquidity", "Cash Ratio",
         format_ratio(cash_ratio(v["cash"], v["current_liabilities"]))),
        ("Liquidity", "Working Capital",
         money(working_capital(v["current_assets"], v["current_liabilities"]))),

        ("Profitability", "Gross Profit Margin",
         format_ratio(gross_profit_margin(v["gross_profit"], v["revenue"]), suffix="%")),
        ("Profitability", "Operating Profit Margin",
         format_ratio(operating_profit_margin(v["operating_profit"], v["revenue"]), suffix="%")),
        ("Profitability", "Net Profit Margin",
         format_ratio(net_profit_margin(v["net_profit"], v["revenue"]), suffix="%")),

        ("Efficiency", "Debtor (Receivables) Turnover",
         format_ratio(debtor_turnover(v["revenue"], v["accounts_receivable"]), suffix="x")),
        ("Efficiency", "Debtor Days",
         format_ratio(debtor_days(v["revenue"], v["accounts_receivable"]), decimals=1, suffix=" days")),
        ("Efficiency", "Inventory Turnover",
         format_ratio(inventory_turnover(v["cost_of_sales"], v["inventory"]), suffix="x")),
        ("Efficiency", "Inventory Days",
         format_ratio(inventory_days(v["cost_of_sales"], v["inventory"]), decimals=1, suffix=" days")),
        ("Efficiency", "Creditor (Payables) Turnover",
         format_ratio(creditor_turnover(v["cost_of_sales"], v["accounts_payable"]), suffix="x")),
        ("Efficiency", "Creditor Days",
         format_ratio(creditor_days(v["cost_of_sales"], v["accounts_payable"]), decimals=1, suffix=" days")),
        ("Efficiency", "Asset Turnover",
         format_ratio(asset_turnover(v["revenue"], v["total_assets"]), suffix="x")),

        ("Leverage", "Debt to Equity",
         format_ratio(debt_to_equity(v["total_debt"], v["equity"]))),
        ("Leverage", "Debt Ratio",
         format_ratio(debt_ratio(v["total_debt"], v["total_assets"]))),
        ("Leverage", "Equity Ratio",
         format_ratio(equity_ratio(v["equity"], v["total_assets"]))),
        ("Leverage", "Interest Coverage Ratio",
         format_ratio(interest_coverage_ratio(v["operating_profit"], v["interest_expense"]), suffix="x")),

        ("Returns", "Return on Equity",
         format_ratio(return_on_equity(v["net_profit"], v["equity"]), suffix="%")),
        ("Returns", "Return on Assets",
         format_ratio(return_on_assets(v["net_profit"], v["total_assets"]), suffix="%")),
        ("Returns", "Return on Capital Employed",
         format_ratio(return_on_capital_employed(v["operating_profit"], v["total_assets"], v["current_liabilities"]), suffix="%")),
    ]


def is_sample_data(prefix):
    return st.session_state.get(f"{prefix}_file_key", "__default__") == "__default__"


def render_sample_data_notice(prefixes):
    """A visible reminder — shown on every page that uses the data, not
    just Home — when a company is still showing the bundled demo figures
    rather than something the user uploaded. Without this, it's easy to
    generate and hand someone a report full of fictitious numbers without
    realising nothing was ever uploaded."""
    names = []
    for prefix in prefixes:
        if is_sample_data(prefix):
            names.append(company_name_a if prefix == "a" else company_name_b)
    if names:
        styled_note(
            f"Showing <b>sample data</b> for {' and '.join(names)} — upload a file "
            f"in the sidebar to analyze real figures instead.",
            "info",
        )


def render_extraction_warning(prefix):
    """Surfaces a file-reading problem on whichever page the user is
    actually looking at, not only on the Home page — someone who jumps
    straight to Ratio Analysis should still be told their numbers are 0
    because the file couldn't be read, not left to assume the tool is
    just broken."""
    msg = st.session_state.get(f"{prefix}_extract_error")
    if msg:
        label = company_name_a if prefix == "a" else company_name_b
        styled_note(f"<b>{label}:</b> {msg}", "warning")


def render_company_name_field(prefix):
    file_key = st.session_state.get(f"{prefix}_file_key", "default")
    key_suffix = re.sub(r"[^a-zA-Z0-9_]", "_", str(file_key))
    default_name = st.session_state.get(f"{prefix}_default_company_name", "")
    name = st.text_input(
        "Company name (used on the report)",
        value=default_name,
        key=f"widget_{prefix}_company_name_{key_suffix}",
    )
    st.session_state[f"{prefix}_company_name"] = name.strip()
    st.caption("Auto-filled from the uploaded file's name — edit if you'd like it to read differently.")


def render_data_review(prefix, title):
    render_company_name_field(prefix)

    error = st.session_state.get(f"{prefix}_extract_error")
    if error:
        styled_note(error, "warning")

    meta = st.session_state.get(f"{prefix}_meta", {})
    match_info = meta.get("match_info", {})
    if meta.get("detected_year"):
        other_years = [y for y in meta.get("available_years", []) if y != meta["detected_year"]]
        years_note = f" · detected year: **{meta['detected_year']}**"
        if other_years:
            years_note += f" (also found: {other_years} — edit figures below if you'd rather use a different year)"
        st.caption(f"Source column: **{meta.get('value_column', '?')}**{years_note}")

    values = st.session_state[f"{prefix}_values"]
    # Widget keys include the current file identity so that uploading a new
    # file creates fresh widgets with the newly-detected values. Without
    # this, Streamlit would keep showing each field's *previous* value —
    # passing a new `value=` to an existing widget key is ignored once
    # that key already has a stored value.
    file_key = st.session_state.get(f"{prefix}_file_key", "default")
    key_suffix = re.sub(r"[^a-zA-Z0-9_]", "_", str(file_key))

    for group_title, group_metrics in FIELD_GROUPS:
        st.markdown(
            f"<div style='color:{MUTED}; font-size:0.78rem; font-weight:700; "
            f"text-transform:uppercase; letter-spacing:0.07em; margin:1.1rem 0 0.4rem 0;'>"
            f"{group_title}</div>",
            unsafe_allow_html=True,
        )
        cols = st.columns(2)
        for i, metric in enumerate(group_metrics):
            with cols[i % 2]:
                label = METRIC_LABELS[metric]
                if metric in OPTIONAL_METRICS:
                    label += " (optional)"
                new_val = st.number_input(
                    label,
                    value=float(values.get(metric, 0.0)),
                    key=f"widget_{prefix}_{metric}_{key_suffix}",
                    step=100.0,
                    format="%.2f"
                )
                values[metric] = new_val
                info = match_info.get(metric)
                if info:
                    st.caption(f"Matched \"{info['matched_label']}\" ({info['confidence']*100:.0f}% confidence)")
                elif metric in OPTIONAL_METRICS:
                    st.caption("Not detected — not all statements report this; leave as 0 if not applicable")
                else:
                    st.caption("Not detected — enter manually")
    st.session_state[f"{prefix}_values"] = values


uploaded_file_a = st.sidebar.file_uploader(
    "Upload Company A file",
    type=["xlsx", "xls", "csv", "pdf"],
    key="uploader_a"
)
uploaded_file_b = st.sidebar.file_uploader(
    "Upload Company B file (optional)",
    type=["xlsx", "xls", "csv", "pdf"],
    key="uploader_b"
)

st.sidebar.caption(
    "Works with almost any financial statement — Excel, CSV, or a "
    "text-based PDF. Row order and exact account names don't need to "
    "match; figures are auto-detected and shown for review on the Home "
    "page before anything is calculated, so you can fix anything that "
    "wasn't picked up correctly."
)

st.sidebar.markdown(
    f"""
    <div style="margin-top:1.1rem; padding-top:0.9rem; border-top:1px solid {BORDER};
                font-size:0.78rem; color:{MUTED}; line-height:1.5;">
        🔒 <strong style="color:{NAVY};">Your data stays private.</strong>
        Uploaded files are processed in memory for this session only —
        nothing is saved to a server or shared elsewhere.
    </div>
    """,
    unsafe_allow_html=True,
)

sync_company_data("a", uploaded_file_a, "Financial_data.xlsx", "Alpine Retail Ltd")
sync_company_data("b", uploaded_file_b, "financial_data_company_b.xlsx", "Beacon Manufacturing Ltd")

company_a = company_values("a")
company_b = company_values("b")
company_name_a = st.session_state.get("a_company_name") or "Company A"
company_name_b = st.session_state.get("b_company_name") or "Company B"

# ---------- Company A ----------
revenue = company_a["revenue"]
cost_of_sales = company_a["cost_of_sales"]
gross_profit = company_a["gross_profit"]
operating_profit = company_a["operating_profit"]
net_profit = company_a["net_profit"]
interest_expense = company_a["interest_expense"]
inventory = company_a["inventory"]
accounts_receivable = company_a["accounts_receivable"]
cash = company_a["cash"]
current_assets = company_a["current_assets"]
accounts_payable = company_a["accounts_payable"]
current_liabilities = company_a["current_liabilities"]
total_assets = company_a["total_assets"]
total_debt = company_a["total_debt"]
equity = company_a["equity"]

# ---------- Company B ----------
revenue_b = company_b["revenue"]
cost_of_sales_b = company_b["cost_of_sales"]
gross_profit_b = company_b["gross_profit"]
operating_profit_b = company_b["operating_profit"]
net_profit_b = company_b["net_profit"]
interest_expense_b = company_b["interest_expense"]
inventory_b = company_b["inventory"]
accounts_receivable_b = company_b["accounts_receivable"]
cash_b = company_b["cash"]
current_assets_b = company_b["current_assets"]
accounts_payable_b = company_b["accounts_payable"]
current_liabilities_b = company_b["current_liabilities"]
total_assets_b = company_b["total_assets"]
total_debt_b = company_b["total_debt"]
equity_b = company_b["equity"]


def generate_pdf():

    doc = SimpleDocTemplate(
        "financial_report.pdf",
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()
    from reportlab.lib.styles import ParagraphStyle

    BRAND_NAVY = colors.HexColor("#0A1930")
    BRAND_GOLD = colors.HexColor("#9B6526")
    BRAND_SOFT = colors.HexColor("#F3EDE1")

    report_company = company_name_a or "Company A"
    detected_year_a = (st.session_state.get("a_meta") or {}).get("detected_year")
    period_label = f"Financial Year {detected_year_a}" if detected_year_a else "the latest available period"
    a_is_sample = is_sample_data("a")
    b_is_real = not is_sample_data("b")

    # Computed up front so both the narrative paragraphs and the summary
    # table can react to the company's actual figures — a loss-making or
    # highly-geared company must not read back the same "healthy, moderate
    # risk" language a strong one would get.
    curr_ratio = current_ratio(current_assets, current_liabilities)
    de_ratio = debt_to_equity(total_debt, equity)
    roe = return_on_equity(net_profit, equity)
    gp_margin = gross_profit_margin(gross_profit, revenue)
    np_margin = net_profit_margin(net_profit, revenue)
    inv_turnover = inventory_turnover(cost_of_sales, inventory)

    liquidity_msg, liquidity_sev = liquidity_analysis(curr_ratio)
    debt_msg, debt_sev = debt_analysis(de_ratio)
    profitability_msg, profitability_sev = profitability_analysis(np_margin)
    roe_msg, roe_sev = roe_analysis(roe)
    gross_margin_msg, gross_margin_sev = gross_margin_analysis(gp_margin)

    net_profit_word = "net profit" if net_profit >= 0 else "net loss"
    net_profit_verb = "achieved" if net_profit >= 0 else "recorded"

    title_style = ParagraphStyle(
        "MyTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=28,
        leading=34,
        alignment=1,
        textColor=BRAND_NAVY
    )

    styles["Title"].alignment = TA_LEFT
    styles["Title"].textColor = BRAND_NAVY
    styles["Heading1"].alignment = TA_LEFT
    styles["Heading1"].textColor = BRAND_NAVY
    styles["Heading2"].alignment = TA_LEFT
    styles["Heading2"].textColor = BRAND_NAVY

    story = []
    story.append(
        Paragraph(
            "<b>Financial Ratio Analysis Report</b>",
            title_style
        )
    )
    from reportlab.graphics.shapes import Drawing, Line

    line = Drawing(450, 10)
    gold_line = Line(0, 5, 450, 5)
    gold_line.strokeColor = BRAND_GOLD
    gold_line.strokeWidth = 2
    line.add(gold_line)

    story.append(line)
    story.append(Spacer(1, 25))
    story.append(Spacer(1, 80))

    story.append(
        Paragraph(
            f"<b>Company:</b> {report_company}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Report Period:</b> {period_label}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Date:</b> {datetime.now().strftime('%d %B %Y')}",
            styles["Normal"]
        )
    )

    if a_is_sample:
        story.append(Spacer(1, 10))
        story.append(
            Paragraph(
                "<i>Note: this report was generated from sample/demo data — "
                "upload a real file in the app to produce an actual analysis.</i>",
                styles["Normal"]
            )
        )

    story.append(Spacer(1, 10))
    story.append(
        Paragraph(
            "<i>This report is generated automatically from the figures provided and is "
            "intended for illustrative and educational purposes. It does not constitute "
            "professional accounting, audit, or investment advice — please consult a "
            "qualified accountant before making financial decisions.</i>",
            ParagraphStyle("Disclaimer", parent=styles["Normal"], fontSize=8, textColor=colors.HexColor("#6E6759")),
        )
    )

    story.append(PageBreak())

    story.append(
        Paragraph(
            "<b>Financial Ratio Analysis Report</b>",
            styles["Title"]
        )
    )
    story.append(
        Paragraph(
            f"{report_company} · Generated on: {datetime.now().strftime('%d %B %Y')}",
            styles["Normal"]
        )
    )
    story.append(Spacer(1, 25))

    story.append(
        Paragraph(
            "<b>Executive Summary</b>",
            styles["Heading1"]
        )
    )

    story.append(
        Paragraph(
            f"""
            This report presents a financial analysis of {report_company}'s financial
            performance based on {period_label if detected_year_a else 'its most recent'} financial statements.

            {report_company} generated revenue of {money_fmt(revenue)} and {net_profit_verb} a {net_profit_word}
            of {money_fmt(abs(net_profit))}. Liquidity, profitability and leverage ratios have
            been calculated to evaluate the company's overall financial health and
            operational efficiency.
            """,
            styles["BodyText"]
        )
    )
    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<b>Recommendations</b>",
            styles["Heading1"]
        )
    )

    # Built from the company's actual severities rather than a fixed list —
    # a company already doing well on a measure gets a "maintain" note, not
    # the same generic "improve" instruction as one that's genuinely weak
    # on it, and a company that's simply missing the data gets told so.
    recommendations = []
    if liquidity_sev in ("bad", "medium"):
        recommendations.append(
            "Improve short-term liquidity — current liabilities are close to "
            "or exceeding current assets, which is worth addressing to reduce "
            "the risk of struggling to meet short-term obligations."
            if liquidity_sev == "bad" else
            "Continue building the liquidity buffer — the current ratio is "
            "adequate but has limited headroom above 1."
        )
    elif liquidity_sev == "good":
        recommendations.append("Maintain the current strong liquidity position.")

    if profitability_sev in ("bad", "medium"):
        recommendations.append(
            "Improve profitability by increasing operating efficiency and "
            "reviewing cost control, as net profit margin is currently low."
            if profitability_sev == "bad" else
            "Look for further efficiency gains to build on the current, "
            "moderate profit margin."
        )
    elif profitability_sev == "good":
        recommendations.append("Continue the strong profitability trend.")

    if debt_sev in ("bad", "medium"):
        recommendations.append(
            "Reduce dependence on debt financing and consider a plan to bring "
            "leverage down, as debt is currently high relative to equity."
            if debt_sev == "bad" else
            "Monitor debt levels to avoid excessive financial leverage as the "
            "business grows."
        )
    elif debt_sev == "good":
        recommendations.append("Maintain the current, conservative level of financial leverage.")

    if roe_sev in ("bad", "medium"):
        recommendations.append(
            "Focus on improving shareholder returns, which are currently weak "
            "relative to the equity invested."
            if roe_sev == "bad" else
            "Continue improving shareholder returns through sustainable growth strategies."
        )
    elif roe_sev == "good":
        recommendations.append("Continue delivering strong returns to shareholders.")

    if not recommendations:
        recommendations.append(
            "No specific figures were available to base a recommendation on — "
            "upload a complete set of financial statements for a fuller analysis."
        )

    story.append(
        Paragraph(
            "<br/>".join(f"• {r}" for r in recommendations),
            styles["BodyText"]
        )
    )
    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<b>Detailed Financial Analysis</b>",
            styles["Heading1"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Revenue:</b> The company generated total revenue of {money_fmt(revenue)} during the financial year, indicating the overall level of business activity.",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 8))

    story.append(
        Paragraph(
            f"<b>Gross Profit:</b> {'Gross profit amounted to' if gross_profit >= 0 else 'The company recorded a gross loss of'} {money_fmt(abs(gross_profit))}"
            f"{', demonstrating the company’s ability to generate profit after direct production costs.' if gross_profit >= 0 else ' — cost of sales exceeded revenue for the period.'}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 8))

    story.append(
        Paragraph(
            f"<b>Net Profit:</b> The company {net_profit_verb} a {net_profit_word} of {money_fmt(abs(net_profit))}, "
            f"{'showing its profitability' if net_profit >= 0 else 'reflecting the shortfall'} after all operating expenses, interest and taxes.",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 8))

    story.append(
        Paragraph(
            f"<b>Current Ratio ({format_ratio(curr_ratio)}):</b> {liquidity_msg}. "
            "A current ratio above 1 means current assets exceed current liabilities; "
            "below 1 means they don't, which can signal difficulty meeting short-term obligations.",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 8))

    story.append(
        Paragraph(
            f"<b>Debt-to-Equity Ratio ({format_ratio(de_ratio)}):</b> This ratio measures financial leverage — "
            f"total debt relative to shareholders' equity. {debt_msg}.",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 8))

    story.append(
        Paragraph(
            f"<b>Return on Equity ({format_ratio(roe, suffix='%')}):</b> This ratio measures how effectively the company generates profit from shareholders' investment. A higher percentage indicates stronger financial performance.",
            styles["BodyText"]
        )
    )
    story.append(Spacer(1, 20))
    story.append(
        Paragraph(
            "<b>Financial Ratios</b>",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 10))
    table_data = [
        ["Metric", "Value"],
        ["Revenue", f"{revenue:,.0f}"],
        ["Gross Profit", f"{gross_profit:,.0f}"],
        ["Net Profit", f"{net_profit:,.0f}"],
        ["Current Ratio", format_ratio(curr_ratio)],
        ["Debt to Equity", format_ratio(de_ratio)],
        ["Return on Equity", format_ratio(roe, suffix="%")]
    ]

    table = Table(table_data, colWidths=[220, 120])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.75, colors.HexColor("#DCD3C2")),
        ("BACKGROUND", (0, 1), (-1, -1), BRAND_SOFT),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BRAND_SOFT]),
    ]))

    story.append(table)
    story.append(Spacer(1, 20))

    # ---------------- Ratio Summary & Interpretation ----------------

    ratio_summary_data = [
        ["Metric", "Value", "Interpretation"],
        ["Current Ratio", format_ratio(curr_ratio), liquidity_analysis(curr_ratio)[0]],
        ["Gross Profit Margin", format_ratio(gp_margin, suffix="%"), gross_margin_analysis(gp_margin)[0]],
        ["Net Profit Margin", format_ratio(np_margin, suffix="%"), profitability_analysis(np_margin)[0]],
        ["Inventory Turnover", format_ratio(inv_turnover, suffix="x"), efficiency_analysis(inv_turnover)[0]],
        ["Debt to Equity", format_ratio(de_ratio), debt_analysis(de_ratio)[0]],
        ["Return on Equity", format_ratio(roe, suffix="%"), roe_analysis(roe)[0]],
    ]

    ratio_summary_table = Table(
        ratio_summary_data,
        colWidths=[130, 70, 220]
    )
    ratio_summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.75, colors.HexColor("#DCD3C2")),
        ("BACKGROUND", (0, 1), (-1, -1), BRAND_SOFT),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BRAND_SOFT]),
    ]))

    story.append(
        KeepTogether([
            Paragraph("<b>Ratio Summary & Interpretation</b>", styles["Heading2"]),
            Spacer(1, 10),
            ratio_summary_table
        ])
    )
    story.append(Spacer(1, 20))

    # ---------------- Full Ratio Breakdown ----------------
    # Every ratio computed from the figures on the Home page, not just the
    # five headline ones above — the same underlying numbers as the app's
    # "Full Ratio Breakdown" section, so the report and the app never
    # disagree with each other.

    story.append(PageBreak())
    story.append(Paragraph("<b>Full Ratio Breakdown</b>", styles["Heading1"]))
    story.append(Spacer(1, 6))
    story.append(
        Paragraph(
            "Every ratio calculated from the figures provided, grouped by "
            "category. Ratios show N/A where the underlying figures weren't "
            "available — several are optional fields not every financial "
            "statement reports.",
            styles["BodyText"]
        )
    )
    story.append(Spacer(1, 10))

    breakdown_data = [["Category", "Ratio", "Value"]]
    for cat, label, value in compute_ratio_set(company_a):
        breakdown_data.append([cat, label, value])

    breakdown_table = Table(breakdown_data, colWidths=[90, 210, 120], repeatRows=1)
    breakdown_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.75, colors.HexColor("#DCD3C2")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ("TEXTCOLOR", (0, 1), (0, -1), BRAND_GOLD),
        ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BRAND_SOFT]),
    ]))
    story.append(breakdown_table)
    story.append(Spacer(1, 20))

    # ---------------- Charts ----------------

    money_formatter = FuncFormatter(lambda x, pos: money_fmt(x))
    NAVY_HEX = "#0A1930"
    GOLD_HEX = "#9B6526"

    plt.rcParams["font.family"] = "sans-serif"

    fig1, ax1 = plt.subplots(figsize=(6, 4))
    ax1.bar(
        ["Revenue", "Gross Profit", "Net Profit"],
        [revenue, gross_profit, net_profit],
        color=[NAVY_HEX, GOLD_HEX, "#8C7B5E"],
        width=0.55
    )
    ax1.set_title("Financial Performance", fontsize=13, fontweight="bold", color=NAVY_HEX)
    ax1.set_ylabel("Amount (£)")
    ax1.yaxis.set_major_formatter(money_formatter)
    ax1.spines["top"].set_visible(False)
    ax1.spines["right"].set_visible(False)
    ax1.grid(axis="y", color="#E4DAC8", linewidth=0.8, zorder=0)
    ax1.set_axisbelow(True)
    fig1.tight_layout()
    fig1.savefig("chart.png", dpi=300)
    plt.close(fig1)

    story.append(
        KeepTogether([
            Paragraph("<b>Revenue vs Profit</b>", styles["Heading2"]),
            Spacer(1, 8),
            Image("chart.png", width=350, height=250)
        ])
    )
    story.append(Spacer(1, 20))

    fig2, ax2 = plt.subplots(figsize=(6, 4))
    ax2.bar(
        ["Current Assets", "Current Liabilities"],
        [current_assets, current_liabilities],
        color=[NAVY_HEX, GOLD_HEX],
        width=0.45
    )
    ax2.set_title("Assets vs Liabilities", fontsize=13, fontweight="bold", color=NAVY_HEX)
    ax2.set_ylabel("Amount (£)")
    ax2.yaxis.set_major_formatter(money_formatter)
    ax2.spines["top"].set_visible(False)
    ax2.spines["right"].set_visible(False)
    ax2.grid(axis="y", color="#E4DAC8", linewidth=0.8, zorder=0)
    ax2.set_axisbelow(True)
    fig2.tight_layout()
    fig2.savefig("chart2.png", dpi=300)
    plt.close(fig2)

    story.append(
        KeepTogether([
            Paragraph("<b>Assets vs Liabilities</b>", styles["Heading2"]),
            Spacer(1, 8),
            Image("chart2.png", width=350, height=250)
        ])
    )
    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<b>Conclusion</b>",
            styles["Heading1"]
        )
    )

    # An accurate, data-driven summary rather than a fixed "healthy and
    # stable" line — a report that praises a loss-making, highly-geared
    # company as healthy would be actively misleading to whoever reads it.
    SEV_PHRASE = {
        "good": "a strength",
        "medium": "acceptable, though with room to improve",
        "bad": "a concern",
        "unavailable": "not calculable from the figures provided",
    }
    severities = [liquidity_sev, profitability_sev, debt_sev, roe_sev, gross_margin_sev]
    bad_count = severities.count("bad")
    good_count = severities.count("good")
    if bad_count >= 2:
        overall_assessment = (
            f"Taken together, {report_company} faces some financial challenges that "
            "warrant attention, with more than one of the headline ratios above "
            "falling into the weaker band."
        )
    elif bad_count == 1 or good_count < 3:
        overall_assessment = (
            f"Taken together, {report_company} shows a mixed financial position — "
            "strong in some areas, with room for improvement in others, as set out above."
        )
    else:
        overall_assessment = (
            f"Taken together, {report_company} demonstrates a healthy financial "
            "position and sound operational efficiency across the ratios calculated."
        )

    story.append(
        Paragraph(
            f"""
            During {period_label if detected_year_a else 'the period reviewed'}, {report_company} recorded a
            Current Ratio of {format_ratio(curr_ratio)} ({SEV_PHRASE.get(liquidity_sev, 'not calculable')}),
            a Debt-to-Equity Ratio of {format_ratio(de_ratio)} ({SEV_PHRASE.get(debt_sev, 'not calculable')}),
            and a Return on Equity of {format_ratio(roe, suffix='%')} ({SEV_PHRASE.get(roe_sev, 'not calculable')}).
            {overall_assessment}
            """,
            styles["BodyText"]
        )
    )

    # ---------------- Optional comparison appendix ----------------
    # Only included when Company B is a real upload, not the bundled
    # sample — a "comparison" against fake demo numbers would be
    # misleading in a report meant to go to someone else.

    if b_is_real:
        story.append(PageBreak())
        story.append(
            Paragraph(
                f"<b>Appendix: Comparison with {company_name_b}</b>",
                styles["Heading1"]
            )
        )
        story.append(Spacer(1, 10))
        story.append(Paragraph("<b>Financial Figures</b>", styles["Heading2"]))
        story.append(Spacer(1, 6))

        all_metrics_in_order = [m for _, group in FIELD_GROUPS for m in group]
        raw_data = [["Metric", report_company, company_name_b]]
        for m in all_metrics_in_order:
            raw_data.append([
                METRIC_LABELS[m],
                f"{company_a[m]:,.0f}",
                f"{company_b[m]:,.0f}",
            ])
        raw_table = Table(raw_data, colWidths=[170, 130, 130], repeatRows=1)
        raw_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), BRAND_NAVY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.75, colors.HexColor("#DCD3C2")),
            ("BACKGROUND", (0, 1), (-1, -1), BRAND_SOFT),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BRAND_SOFT]),
        ]))
        story.append(raw_table)
        story.append(Spacer(1, 20))

        story.append(Paragraph("<b>Full Ratio Comparison</b>", styles["Heading2"]))
        story.append(Spacer(1, 6))

        rows_a = compute_ratio_set(company_a)
        rows_b = compute_ratio_set(company_b)
        comparison_data = [["Category", "Ratio", report_company, company_name_b]]
        for (cat, label, val_a), (_, _, val_b) in zip(rows_a, rows_b):
            comparison_data.append([cat, label, val_a, val_b])

        comparison_table = Table(comparison_data, colWidths=[80, 175, 85, 85], repeatRows=1)
        comparison_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), BRAND_NAVY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.75, colors.HexColor("#DCD3C2")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
            ("TEXTCOLOR", (0, 1), (0, -1), BRAND_GOLD),
            ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BRAND_SOFT]),
        ]))
        story.append(comparison_table)

    doc.build(
        story,
        onFirstPage=add_page_number,
        onLaterPages=add_page_number
    )


# ---------------- Top navigation ----------------

if "active_page" not in st.session_state:
    st.session_state["active_page"] = "Home"

render_topbar()
page = st.session_state["active_page"]

# ---------------- Home ----------------

if page == "Home":

    render_page_header(
        "Welcome",
        "Upload a company's financial statements, review the detected figures, "
        "and generate a client-ready ratio analysis report.",
    )

    # A single row of compact tags rather than a paragraph + a 5-item
    # bullet list re-explaining the same thing the subtitle above already
    # said — three stacked layers of "what this tool does" was the main
    # source of the page feeling padded/wordy before getting to the
    # actual data-entry section below.
    st.markdown(
        f"""
        <div style="display:flex; flex-wrap:wrap; gap:0.5rem; margin-top:0.4rem;">
          {"".join(
              f"<span style='background:{PANEL}; border:1px solid {BORDER}; color:{NAVY}; "
              f"font-size:0.78rem; font-weight:600; padding:0.32rem 0.85rem; "
              f"border-radius:20px; white-space:nowrap;'>{tag}</span>"
              for tag in ["Liquidity", "Profitability", "Leverage", "Company Comparison", "PDF Report"]
          )}
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.markdown(
        f"<div style='color:{MUTED}; font-size:0.8rem; margin-top:1.1rem;'>"
        f"Developed by Muniba Ashraf · BSc (Hons) Accounting &amp; Finance</div>",
        unsafe_allow_html=True,
    )

    st.divider()
    st.header("Your Data")
    st.write(
        "These are the figures detected from your upload (or the sample data "
        "if nothing was uploaded). Everything below is editable — fix anything "
        "that wasn't picked up correctly before moving to the other pages."
    )

    tab_a, tab_b = st.tabs([company_name_a, f"{company_name_b} (optional)"])
    with tab_a:
        render_data_review("a", "Company A")
    with tab_b:
        st.caption("Used on the Company Comparison page. Leave this as sample data if you only need one company.")
        render_data_review("b", "Company B")

## ---------------- Ratio Analysis ----------------

elif page == "Ratio Analysis":

    render_page_header(
        "Ratio Analysis Dashboard",
        f"Liquidity, profitability, efficiency, leverage and returns, calculated from {company_name_a}'s data.",
    )

    render_sample_data_notice(["a"])
    render_extraction_warning("a")

    curr_ratio = current_ratio(current_assets, current_liabilities)
    np_margin = net_profit_margin(net_profit, revenue)
    inv_turnover = inventory_turnover(cost_of_sales, inventory)
    de_ratio = debt_to_equity(total_debt, equity)
    roe = return_on_equity(net_profit, equity)

    dashboard_metrics = [
        ("Liquidity", "Current Ratio", format_ratio(curr_ratio)),
        ("Profitability", "Net Profit Margin", format_ratio(np_margin, suffix="%")),
        ("Efficiency", "Inventory Turnover", format_ratio(inv_turnover, suffix="x")),
        ("Leverage", "Debt to Equity", format_ratio(de_ratio)),
        ("Returns", "Return on Equity", format_ratio(roe, suffix="%")),
    ]
    metric_cols = st.columns(5)
    for col, (tag, label, value) in zip(metric_cols, dashboard_metrics):
        with col:
            with st.container(key=f"tile_{tag.lower()}", border=True):
                st.markdown(
                    f"<div style='color:{CATEGORY_COLORS[tag]}; font-size:0.72rem; letter-spacing:0.08em; "
                    f"text-transform:uppercase; font-weight:700;'>{tag}</div>",
                    unsafe_allow_html=True,
                )
                st.metric(label, value)

    st.divider()

    st.subheader("Financial Insights")

    render_insight(liquidity_analysis(curr_ratio))
    render_insight(profitability_analysis(np_margin))
    render_insight(efficiency_analysis(inv_turnover))
    render_insight(debt_analysis(de_ratio))
    render_insight(roe_analysis(roe))

    st.divider()

    st.subheader("Full Ratio Breakdown")
    st.caption(
        "Every ratio calculated from the figures on the Home page, grouped the "
        "way an accountant would work through a set of statements. Ratios "
        "show N/A where the underlying figures weren't provided — most are "
        "optional fields not every financial statement reports."
    )

    ratio_rows = compute_ratio_set(company_a)
    for category in RATIO_CATEGORIES:
        st.markdown(
            f"<div style='color:{CATEGORY_COLORS[category]}; font-size:0.78rem; font-weight:700; "
            f"text-transform:uppercase; letter-spacing:0.07em; margin:1.1rem 0 0.4rem 0;'>{category}</div>",
            unsafe_allow_html=True,
        )
        cat_df = pd.DataFrame(
            [(label, value) for cat, label, value in ratio_rows if cat == category],
            columns=["Ratio", company_name_a],
        )
        st.dataframe(cat_df, hide_index=True, width="stretch")

    st.divider()

    st.subheader("Financial Performance")

    chart_option = st.selectbox(
        "Choose a chart",
        [
            "Revenue vs Profit",
            "Assets vs Liabilities",
            "Debt vs Equity",
            "Debtors vs Creditors"
        ]
    )

    if chart_option == "Revenue vs Profit":

        chart_data = pd.DataFrame(
            {
                "Amount": [
                    revenue,
                    gross_profit,
                    net_profit
                ]
            },
            index=[
                "Revenue",
                "Gross Profit",
                "Net Profit"
            ]
        )

    elif chart_option == "Assets vs Liabilities":

        chart_data = pd.DataFrame(
            {
                "Amount": [
                    current_assets,
                    current_liabilities
                ]
            },
            index=[
                "Current Assets",
                "Current Liabilities"
            ]
        )

    elif chart_option == "Debt vs Equity":

        chart_data = pd.DataFrame(
            {
                "Amount": [
                    total_debt,
                    equity
                ]
            },
            index=[
                "Total Debt",
                "Equity"
            ]
        )

    elif chart_option == "Debtors vs Creditors":

        chart_data = pd.DataFrame(
            {
                "Amount": [
                    accounts_receivable,
                    accounts_payable
                ]
            },
            index=[
                "Accounts Receivable",
                "Accounts Payable"
            ]
        )

    # Show the chart for ALL options
    render_chart_or_table(chart_data, key="ratio_performance")

# ---------------- Company Comparison ----------------

elif page == "Company Comparison":

    render_page_header(
        "Company Comparison",
        f"{company_name_a} against {company_name_b} — raw figures and calculated ratios side by side.",
    )

    render_sample_data_notice(["a", "b"])
    render_extraction_warning("a")
    render_extraction_warning("b")

    all_metrics_in_order = [m for _, group in FIELD_GROUPS for m in group]
    comparison_df = pd.DataFrame(
        {
            company_name_a: [company_a[m] for m in all_metrics_in_order],
            company_name_b: [company_b[m] for m in all_metrics_in_order],
        },
        index=[METRIC_LABELS[m] for m in all_metrics_in_order],
    )

    st.subheader("Financial Comparison")
    st.dataframe(comparison_df, width="stretch")

    st.subheader("Comparison Chart")

    chart_metric = st.selectbox(
        "Select Metric",
        comparison_df.index
    )

    chart_df = pd.DataFrame(
        {
            "Amount": comparison_df.loc[chart_metric]
        }
    )

    render_chart_or_table(chart_df, color=NAVY_LIGHT, key="comparison_chart")

    # ---------------- Ratio Comparison ----------------

    st.divider()
    st.subheader("Ratio Comparison")
    st.caption(
        "The full ratio set for both companies, side by side, grouped by category. "
        "Shown as tables rather than charts since ratios use very different scales "
        "(multiples, percentages, days) that a single chart would misrepresent."
    )

    rows_a = compute_ratio_set(company_a)
    rows_b = compute_ratio_set(company_b)
    for category in RATIO_CATEGORIES:
        st.markdown(
            f"<div style='color:{CATEGORY_COLORS[category]}; font-size:0.78rem; font-weight:700; "
            f"text-transform:uppercase; letter-spacing:0.07em; margin:1.1rem 0 0.4rem 0;'>{category}</div>",
            unsafe_allow_html=True,
        )
        cat_df = pd.DataFrame(
            [
                (label_a, val_a, val_b)
                for (cat_a, label_a, val_a), (_, _, val_b) in zip(rows_a, rows_b)
                if cat_a == category
            ],
            columns=["Ratio", company_name_a, company_name_b],
        )
        st.dataframe(cat_df, hide_index=True, width="stretch")

    # ---------------- Financial Report ----------------

elif page == "Financial Report":

    render_page_header(
        "Financial Report",
        f"Generate a polished, multi-page PDF for {company_name_a} — cover page, "
        "executive summary, ratio analysis and charts — ready to share.",
    )

    render_sample_data_notice(["a"])
    render_extraction_warning("a")

    with st.container(border=True):
        b_note = (
            f" A comparison appendix with {company_name_b} will be included "
            f"automatically since you've uploaded a file for them too."
            if not is_sample_data("b") else
            " Upload a Company B file in the sidebar to also include a "
            "comparison appendix."
        )
        st.markdown(
            f"<div style='font-weight:700; color:{NAVY}; font-size:1.05rem;'>"
            f"Financial Ratio Analysis Report</div>"
            f"<div style='color:{MUTED}; font-size:0.88rem; margin-top:0.25rem;'>"
            f"Includes an executive summary, recommendations, a detailed ratio "
            f"write-up, a summary table with interpretations, and two charts "
            f"(Revenue vs Profit, Assets vs Liabilities) — labelled with "
            f"{company_name_a}'s name throughout, not ours.{b_note}</div>",
            unsafe_allow_html=True,
        )
        st.write("")

        if st.button("Generate PDF Report"):

            with st.spinner("Generating PDF report..."):
                generate_pdf()

            with open("financial_report.pdf", "rb") as pdf_file:

                st.download_button(
                    label="Download PDF Report",
                    data=pdf_file,
                    file_name="financial_report.pdf",
                    mime="application/pdf"
                )

            styled_note("Report generated successfully.", "good")

# ---------------- About ----------------

elif page == "About":

    render_page_header(
        "About",
        "The person behind this tool, and how to get in touch.",
    )

    with st.container(border=True):
        st.markdown(
            f"""
            <div style="font-family:'Source Serif 4', Georgia, serif; font-weight:700;
                        font-size:1.3rem; color:{NAVY}; margin-bottom:0.6rem;">
                Muniba Ashraf
            </div>
            <div style="color:{MUTED}; font-size:0.98rem; line-height:1.7; max-width:640px;">
                I'm a First Class Accounting &amp; Finance graduate with an interest in where
                accounting meets code. During my degree, I kept noticing how mechanical ratio
                analysis really is — the same fifteen to twenty ratios, recalculated by hand,
                for every set of financial statements. So I built this tool to take that first
                stage off an accountant's hands: upload a company's statements in whatever
                format they happen to be in, and it extracts the figures, calculates the full
                ratio set, and generates a client-ready report — while leaving the actual
                judgement to you.
            </div>
            """,
            unsafe_allow_html=True,
        )

        st.markdown(
            f"""
            <div style="display:flex; flex-wrap:wrap; gap:0.5rem; margin-top:1.1rem;">
              {"".join(
                  f"<span style='background:{PANEL}; border:1px solid {BORDER}; color:{NAVY}; "
                  f"font-size:0.78rem; font-weight:600; padding:0.32rem 0.85rem; "
                  f"border-radius:20px; white-space:nowrap;'>{tag}</span>"
                  for tag in ["BSc (Hons) Accounting & Finance — First Class", "Python", "Streamlit"]
              )}
            </div>
            """,
            unsafe_allow_html=True,
        )

    st.write("")
    st.subheader("Get in touch")
    st.markdown(
        f"""
        <div style="display:flex; flex-wrap:wrap; gap:0.7rem; margin-top:0.4rem;">
          <a class="about-contact-link" href="mailto:munibaashraf48@gmail.com">
            ✉️ munibaashraf48@gmail.com
          </a>
          <a class="about-contact-link" href="https://www.linkedin.com/in/muniba-ashraf/" target="_blank">
            💼 LinkedIn
          </a>
        </div>
        """,
        unsafe_allow_html=True,
    )
